steps:
- name: node:14.18.0-alpine
  entrypoint: yarn
  args: ['install']
- name: node:14.18.0-alpine
  entrypoint: yarn
  args: ['build']
- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "rsync", "-d", "-r", "build", "gs://us.gcr.io/nth-canyon-230223"]

- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "acl", "ch", "-u", "AllUsers:R", "gs://us.gcr.io/nth-canyon-230223/**"]